# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "dotenv", "~> 2.7"

gem "tty-prompt", "~> 0.23.0"

gem "tty-table", "~> 0.12.0"

gem "json", "~> 2.5"

gem "iex-ruby-client", "~> 1.4"
